---
- name: Install nginx
  apt: name=nginx state=installed update_cache=yes

- name: Start nginx
  service: name=nginx state=running enabled=yes

- name: Install php components (fpm)
  apt: name={{item}} state=present
  with_items:
    - php5-fpm
    - php5-cgi
    - php5-mcrypt
    - php5-gd
    - php5-curl
    - php-pear

- name: set cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0

- name: Restart nginx
  service: name=nginx state=restarted

- name: Restart php5-fpm
  service: name=php5-fpm state=restarted