---
- name: Add stretch backports
  apt_repository: repo='deb http://ftp.uk.debian.org/debian/ stretch main contrib non-free' state=present
  become: yes

- name: Update apt
  shell: "apt-get update"
  become: yes

- name: Install java8 headless
  shell: "apt-get install -y --no-install-recommends openjdk-8-jre-headless"
  become: yes

- name: Remove stretch.list and clean
  shell: "rm /etc/apt/sources.list.d/ftp_uk_debian_org_debian.list && apt-get clean"
  become: yes
