---
- name: Add stretch backports
  apt_repository: repo='deb http://ftp.uk.debian.org/debian/ stretch main contrib non-free' state=present

- name: Update apt
  shell: "sudo apt-get update"

- name: Install java8 headless
  shell: "sudo apt-get install -y --no-install-recommends openjdk-8-jre-headless"

- name: Remove stretch.list and clean
  shell: "sudo rm /etc/apt/sources.list.d/ftp_uk_debian_org_debian.list && apt-get clean"
